name: Build and Deploy WebGL
on:
    [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          
        - uses: game-ci/unity-test-runner@v4.3.1
          env:
              UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
              UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
              projectPath: src
              unityVersion: 2022.3.15f1
              
        - uses: game-ci/unity-builder@v4
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: WebG
            projectPath: src
            
        - uses: actions/upload-artifact@v2
          with:
            name: WebGL-Build
            path: src/Build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v2
        with:
          name: WebGL-Build
          path: src/Build/WebGL

      - uses: peaceiris/actions-gh-pages@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/Build